spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    org.springframework.r2dbc: debug

jwt:
  access-token:
    key: VlwEyVBsYt9V7zq57TejMnVUyZblYcfPQye08f7MgAA9XkHa
    expiration-time: 10
  refresh-token:
    key: VlwEyVBsYt9V7zq57TejMnVUyZblYcfPQye08f7MgAA9XkHa
    expiration-time: 60

management:
  endpoints:
    web:
      exposure:
        include: "*"