logging:
  level:
    org.springframework.r2dbc: debug

jwt:
  access-token:
    key: QpBdfsWyplp6z4I/DuwSNdQ78PGOI2Zu4G+f5Gdh9AQ=
    expiration-time: 10
  refresh-token:
    key: w7H4KoQ5KD9Hy4/wG0qZpspGe5YNNOAj/YyBkouN6Gs=
    expiration-time: 60

management:
  endpoints:
    web:
      exposure:
        include: "*"