logging:
  level:
    org.springframework.r2dbc: debug

---

spring:
  config:
    activate:
      on-profile: mysql
  r2dbc:
    url: r2dbc:mysql://localhost:3306/shop
    username: root
    password: root

---

spring:
  config:
    activate:
      on-profile: postgres
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/shop
    username: postgres
    password: postgres